---

- name: Begin Install of filebeat client
  shell: figlet Begin Install of filebeat client > /dev/tty
  delegate_to: localhost

- name: Importing the Elasticsearch public GPG key to the rpm package manager
  rpm_key:
    state: present
    key: http://packages.elastic.co/GPG-KEY-elasticsearch

- name: Copying filebeat.repo.repo file to /etc/yum.repos.d/ directory
  copy:
    src: filebeat.repo
    dest: /etc/yum.repos.d/

- name: Installing filebeat...!!!
  yum:
     name: filebeat
     state: latest
     update_cache: yes

- name: start and enable the filebeat service
  service:
    name: filebeat
    state: started
    enabled: yes

- name: Removing filebeat.yml file
  file:
    path: /etc/filebeat/filebeat.yml
    state: absent

- name: Configuring Filebeat
  template:
    src: filebeat_template.yml
    dest: /etc/filebeat/filebeat.yml
  notify: restart filebeat

- name: restart filebeat
  service: 
    name: filebeat
    state: restarted
