---

- name: Installing Packages as Prequisites...
  shell: figlet Installing Packages as Prequisites > /dev/tty
  delegate_to: localhost

- name: Update CentOS System
  yum:
     name: "*"
     state: latest
     update_cache: yes

- name: Installing openjdk 1.8.0_171 version
  yum:
     name: java-1.8.0-openjdk.x86_64 
     state: latest
     update_cache: yes

- name: Install libselinux as prerequisite for SELinux Ansible module
  yum:
    name: "{{item}}"
    state: latest
  with_items:
    - libselinux-python
    - libsemanage-python

- name: Set SELinux in permissive mode until the machine is rebooted
  shell: setenforce 0
  ignore_errors: true

include: elasticsearch.yml
include: logstash.yml
include: kibana.yml
