---

- name: Installing Packages as Prequisites...
  shell: figlet Installing Packages as Prequisites > /dev/tty
  delegate_to: localhost

- name: Update CentOS System
  yum:
     name: "*"
     state: latest
     update_cache: yes

- name: Installing openjdk 1.8.0_171 version
  yum:
     name: java-1.8.0-openjdk.x86_64 
     state: latest
     update_cache: yes

- include_tasks: elasticsearch.yml
- include_tasks: logstash.yml
- include_tasks: kibana.yml
