---

- name: generating ssh key for root
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Create hosts all file
  shell: cat {{ Inventory_Path }} | grep -v '#' | grep -v '\[' | grep -v '/n'| grep -v '^$' > temphosts

- name: Copy SSH keys on remote server
  shell: sh ./roles/ssh_auth/files/sshkeycopy.sh

- name: figlet rpm install via yum
  yum:
    name: "{{ ANSIBLE_SCRIPT_PATH }}/roles/ssh_auth/files/figlet-2.2.5-9.el7.x86_64.rpm"
    state: present
  ignore_errors: True
